"""
Streamlit UI for the Obsidian Vault RAG Assistant.

Run locally:
    streamlit run src/app.py

Requires GROQ_API_KEY (and optionally OPENAI_API_KEY as fallback) set as
environment variables or Streamlit secrets.
"""

import os
import streamlit as st
from dotenv import load_dotenv

from index_store import VaultIndex
from generate import generate_answer

st.set_page_config(page_title="Obsidian Vault RAG Assistant", page_icon="🧠", layout="wide")

VAULT_DIR = os.path.join(os.path.dirname(__file__), "..", "vault")


@st.cache_resource(show_spinner="Indexing your vault (first run only)...")
def get_index():
    idx = VaultIndex()
    idx.build(VAULT_DIR)
    return idx

def load_api_keys():
    # Local dev: load from a .env file in the project root, if present.
    load_dotenv()

    # Cloud deployment: Streamlit secrets. st.secrets is lazy — it only raises
    # FileNotFoundError the moment something actually iterates/checks it (e.g.
    # `key in st.secrets`), not on attribute access, so the guard has to wrap
    # that check itself rather than the `st.secrets` reference.
    for key in ("GROQ_API_KEY", "OPENAI_API_KEY"):
        try:
            if key in st.secrets:
                os.environ[key] = st.secrets[key]
        except FileNotFoundError:
            break  # no secrets.toml at all locally — .env above already handled it


load_api_keys()



st.title("🧠 Obsidian Vault RAG Assistant")
st.caption(
    "Ask questions about the notes in this vault. Answers are grounded in "
    "retrieved note excerpts, with sources cited."
)

with st.sidebar:
    st.subheader("About this vault")
    st.write(
        "Demo vault: a mix of general AI/ML notes (RAG, embeddings, "
        "agentic AI, MLOps) and personal project notes (DocuMind, job "
        "search, career goals), interlinked with Obsidian-style "
        "`[[wikilinks]]`."
    )
    top_k = st.slider("Chunks retrieved per question", min_value=2, max_value=8, value=4)
    st.divider()
    st.caption("Built for The Skillians — Generative AI Developer Intern Build Sprint")

if not os.environ.get("GROQ_API_KEY") and not os.environ.get("OPENAI_API_KEY"):
    st.warning(
        "No LLM API key found. Set GROQ_API_KEY (or OPENAI_API_KEY) as an "
        "environment variable or in Streamlit secrets to enable answers."
    )

index = get_index()
st.success(f"Indexed {index.count()} chunks from the vault.", icon="✅")

if "messages" not in st.session_state:
    st.session_state.messages = []

for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])
        if msg.get("sources"):
            with st.expander("Sources"):
                for s in msg["sources"]:
                    st.markdown(f"- **{s['note_title']}** — *{s['heading']}*")

question = st.chat_input("Ask something about the vault...")

if question:
    st.session_state.messages.append({"role": "user", "content": question})
    with st.chat_message("user"):
        st.markdown(question)

    with st.chat_message("assistant"):
        with st.spinner("Retrieving relevant notes..."):
            hits = index.query(question, top_k=top_k)

        with st.spinner("Generating answer..."):
            try:
                result = generate_answer(question, hits)
                answer_text = result["answer"]
                st.markdown(answer_text)
                st.caption(f"Generated by {result['provider']}")
            except Exception as e:
                answer_text = f"Sorry, I couldn't generate an answer: {e}"
                st.error(answer_text)

        with st.expander("Sources"):
            for h in hits:
                st.markdown(f"- **{h['note_title']}** — *{h['heading']}*")

    st.session_state.messages.append({
        "role": "assistant",
        "content": answer_text,
        "sources": hits,
    })
